-- ============================================================================
-- FIX: document_chunks.embedding column type
-- ============================================================================
-- ISSUE: embedding column is USER-DEFINED instead of vector(768)
-- IMPACT: Vector search fails, falls back to slow keyword-only search
-- ============================================================================

BEGIN;

-- 1. Check current column type
DO $$
DECLARE
    current_type text;
BEGIN
    SELECT data_type INTO current_type
    FROM information_schema.columns
    WHERE table_name = 'document_chunks' 
      AND column_name = 'embedding';
    
    RAISE NOTICE 'Current embedding column type: %', current_type;
END $$;

-- 2. Drop existing HNSW index (will recreate after fixing column)
DROP INDEX IF EXISTS idx_document_chunks_embedding_hnsw;

-- 3. Fix the embedding column type
-- If embeddings already exist, preserve them; otherwise set to NULL
ALTER TABLE document_chunks 
  ALTER COLUMN embedding TYPE vector(768)
  USING CASE 
    WHEN embedding IS NOT NULL THEN embedding::vector(768)
    ELSE NULL::vector(768)
  END;

-- 4. Recreate HNSW index for fast vector search
CREATE INDEX idx_document_chunks_embedding_hnsw 
ON document_chunks 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- 5. Add comment
COMMENT ON COLUMN document_chunks.embedding IS 'Vector embedding (768 dimensions) for semantic search. Generated by text-embedding-004 model.';

COMMIT;

-- Verification
DO $$
DECLARE
    col_type text;
    idx_count int;
    embedding_count int;
    total_count int;
BEGIN
    -- Check column type
    SELECT data_type INTO col_type
    FROM information_schema.columns
    WHERE table_name = 'document_chunks' 
      AND column_name = 'embedding';
    
    -- Check index
    SELECT COUNT(*) INTO idx_count
    FROM pg_indexes
    WHERE tablename = 'document_chunks' 
      AND indexdef LIKE '%hnsw%';
    
    -- Check embeddings for sculptai tenant
    SELECT 
      COUNT(*) FILTER (WHERE embedding IS NOT NULL),
      COUNT(*)
    INTO embedding_count, total_count
    FROM document_chunks
    WHERE tenant_id = 'b89b8fab-0a25-4266-a4d0-306cc4d358cb';
    
    RAISE NOTICE '========================================';
    RAISE NOTICE 'VERIFICATION RESULTS:';
    RAISE NOTICE '========================================';
    
    IF col_type = 'USER-DEFINED' THEN
        RAISE NOTICE '✅ Column type: % (vector)', col_type;
    ELSE
        RAISE NOTICE '❌ Column type: % (expected USER-DEFINED for vector)', col_type;
    END IF;
    
    IF idx_count > 0 THEN
        RAISE NOTICE '✅ HNSW index: EXISTS';
    ELSE
        RAISE NOTICE '❌ HNSW index: MISSING';
    END IF;
    
    RAISE NOTICE '📊 Embeddings for sculptai: % out of % chunks', embedding_count, total_count;
    
    IF embedding_count = 0 AND total_count > 0 THEN
        RAISE NOTICE '⚠️  WARNING: No embeddings found! You need to:';
        RAISE NOTICE '    1. Re-process existing documents, OR';
        RAISE NOTICE '    2. Run embedding generation job for existing chunks';
    ELSIF embedding_count < total_count THEN
        RAISE NOTICE '⚠️  WARNING: Some chunks missing embeddings (% out of %)', total_count - embedding_count, total_count;
    ELSE
        RAISE NOTICE '✅ All chunks have embeddings!';
    END IF;
    
    RAISE NOTICE '========================================';
END $$;

